// <auto-generated/>
using System;
using System.Diagnostics;
using System.IO;
namespace N15
{
    /// <summary>
    /// This class performs an important function.
    /// </summary>
    internal class Program
    {
        private static void Main()
        {
            //var start = new Stopwatch();

            //start.Start();

            ReadOnlySpan<byte> buffer = new ReadOnlySpan<byte>();
            string filePath = @"D:\c#Projects\HomeWorkSolution\N15\TextBlock\Hello.txt";
            if (!File.Exists(filePath))
            {
                using (StreamWriter streamWriter = File.CreateText(filePath))
                {
                    var s = streamWriter.BaseStream;
                    streamWriter.WriteLine("1 - text");
                    streamWriter.WriteLine("2 - text");
                    streamWriter.WriteLine("4 - text");
                }
            }

            using (StreamReader streamReader = File.OpenText(filePath))
            {
                var words = streamReader.Read();

                Console.WriteLine(words);

            }

            //start.Stop();
            //Console.WriteLine(start.ElapsedMilliseconds);


        }
    }
}